kind: pipeline
name: default

steps:
  - name: test
    image: ubuntu:18.04
    pull: always
    environment:
      RUN_BUILD: "true"
      RUN_TESTS: "true"
      RUN_COVERAGE: "true"
    commands:
      - /bin/bash -c "./travis_ci.sh"
